# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-12-07 11:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('municipal_finance', '0032_aged_creditor_items_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalityStaffContactsUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='uploads/municipality_staff_contacts/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'municipality_staff_contacts_update',
            },
        ),
        migrations.RemoveField(
            model_name='municipalitystaffcontactsupload',
            name='user',
        ),
        migrations.DeleteModel(
            name='MunicipalityStaffContactsUpload',
        ),
    ]
