# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-12-07 11:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('municipal_finance', '0033_auto_20201207_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalStaffContactsUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='uploads/municipal_staff_contacts/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'municipal_staff_contacts_update',
            },
        ),
        migrations.RenameModel(
            old_name='MunicipalityStaffContacts',
            new_name='MunicipalStaffContacts',
        ),
        migrations.RemoveField(
            model_name='municipalitystaffcontactsupdate',
            name='user',
        ),
        migrations.AlterModelTable(
            name='municipalstaffcontacts',
            table='municipal_staff_contacts',
        ),
        migrations.DeleteModel(
            name='MunicipalityStaffContactsUpdate',
        ),
    ]
