# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-12-14 07:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('municipal_finance', '0033_auto_20201211_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgedCreditorsV2Update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BigIntegerField(null=True)),
                ('inserted', models.BigIntegerField(null=True)),
                ('file', models.FileField(max_length=255, upload_to='updates/aged_creditors_v2/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aged_creditors_v2_update',
            },
        ),
        migrations.CreateModel(
            name='AgedDebtorsV2Update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BigIntegerField(null=True)),
                ('inserted', models.BigIntegerField(null=True)),
                ('file', models.FileField(max_length=255, upload_to='updates/aged_debtors_v2/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aged_debtors_v2_update',
            },
        ),
    ]
