# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-12-11 10:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('municipal_finance', '0035_auto_20201211_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowV2Update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BigIntegerField(null=True)),
                ('inserted', models.BigIntegerField(null=True)),
                ('file', models.FileField(max_length=255, upload_to='updates/cash_flow_v2/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cash_flow_v2_update',
            },
        ),
        migrations.AddField(
            model_name='municipalstaffcontactsupdate',
            name='deleted',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='municipalstaffcontactsupdate',
            name='inserted',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='incomeexpenditurev2update',
            name='file',
            field=models.FileField(max_length=255, upload_to='updates/income_expenditure_v2/'),
        ),
        migrations.AlterModelTable(
            name='incomeexpenditurev2update',
            table='income_expenditure_v2_update',
        ),
    ]
